In [74]:
from __future__ import print_function
import torch
import numpy as np

In [15]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -0.0000e+00,  3.7367e-29],
        [-1.5849e+29,         nan, -4.5461e+24],
        [ 1.3443e+22,  5.3780e+22,  2.0892e+20],
        [ 5.4169e-05,  1.6875e-07,  2.6077e-09],
        [ 1.3423e-05,  1.3310e+22,  2.4428e-31]])


In [16]:
x = torch.rand(3, 4)
print(x)

tensor([[ 0.7457,  0.9644,  0.5663,  0.8096],
        [ 0.1773,  0.3009,  0.3126,  0.2325],
        [ 0.8939,  0.0560,  0.2183,  0.3200]])


In [23]:
x = torch.zeros(4, 5, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]])


In [24]:
x = torch.tensor([[2.23, 1.55], [1.0, 2.0]])
print(x)

tensor([[ 2.2300,  1.5500],
        [ 1.0000,  2.0000]])


In [29]:
x.new_ones(3, 3)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [31]:
print(x.size())

torch.Size([2, 2])


In [36]:
y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[-0.7294,  1.4812],
        [ 0.4717, -0.2567]])


In [37]:
x + y

tensor([[ 1.5006,  3.0312],
        [ 1.4717,  1.7433]])

In [43]:
x
x.t_()

tensor([[ 2.2300,  1.5500],
        [ 1.0000,  2.0000]])

In [44]:
x = y

In [46]:
print(y)
print(x)

tensor([[-0.7294,  1.4812],
        [ 0.4717, -0.2567]])
tensor([[-0.7294,  1.4812],
        [ 0.4717, -0.2567]])


In [47]:
x.add_(1)

tensor([[ 0.2706,  2.4812],
        [ 1.4717,  0.7433]])

In [48]:
print(y)

tensor([[ 0.2706,  2.4812],
        [ 1.4717,  0.7433]])


In [50]:
y.copy_(x)

tensor([[ 0.2706,  2.4812],
        [ 1.4717,  0.7433]])

In [58]:
z = y.clone()

In [59]:
z.add_(1.0)

tensor([[ 2.2706,  4.4812],
        [ 3.4717,  2.7433]])

In [60]:
print(x)

tensor([[ 1.2706,  3.4812],
        [ 2.4717,  1.7433]])


In [61]:
print(y)

tensor([[ 1.2706,  3.4812],
        [ 2.4717,  1.7433]])


In [64]:
y.numpy()

array([[1.2705758, 3.4811933],
       [2.4717336, 1.7432573]], dtype=float32)

In [70]:
yy = y.view(y.size()[0] * y.size()[1])
print(yy)

tensor([ 1.2706,  3.4812,  2.4717,  1.7433])


In [71]:
yy += 1

In [72]:
print(yy)

tensor([ 2.2706,  4.4812,  3.4717,  2.7433])


In [73]:
print(y)

tensor([[ 2.2706,  4.4812],
        [ 3.4717,  2.7433]])


In [81]:
y = torch.from_numpy( np.ones([3, 3]) )

In [82]:
print(y)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [83]:
torch.cuda.is_available()

False