In [3]:
from __future__ import print_function
import torch
import torch.nn as nn
import numpy as np

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.1704e-41],
        [ 0.0000e+00,  2.2369e+08,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [        nan,         nan, -6.2882e+16]])


In [45]:
x = torch.rand(1, 3, 4)
print(x, x.size())

tensor([[[0.6765, 0.0277, 0.6467, 0.9710],
         [0.4222, 0.4742, 0.6792, 0.9473],
         [0.2155, 0.7642, 0.4377, 0.4843]]]) torch.Size([1, 3, 4])


In [53]:
x[0, :, 0]

tensor([0.6765, 0.4222, 0.2155])

In [43]:
z = x.squeeze()
print(z, z.shape)

tensor([0.4739, 0.4129, 0.2577, 0.2689, 0.7058, 0.0229]) torch.Size([6])


In [18]:
import random
random.choice([(1, 3), (2, 4), (1,1)])

(2, 4)

In [9]:
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
x = torch.zeros(4, 5, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]])


In [24]:
x = torch.tensor([[2.23, 1.55], [1.0, 2.0]])
print(x)

tensor([[ 2.2300,  1.5500],
        [ 1.0000,  2.0000]])


In [29]:
x.new_ones(3, 3)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [31]:
print(x.size())

torch.Size([2, 2])


In [36]:
y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[-0.7294,  1.4812],
        [ 0.4717, -0.2567]])


In [37]:
x + y

tensor([[ 1.5006,  3.0312],
        [ 1.4717,  1.7433]])

In [43]:
x
x.t_()

tensor([[ 2.2300,  1.5500],
        [ 1.0000,  2.0000]])

In [44]:
x = y

In [46]:
print(y)
print(x)

tensor([[-0.7294,  1.4812],
        [ 0.4717, -0.2567]])
tensor([[-0.7294,  1.4812],
        [ 0.4717, -0.2567]])


In [47]:
x.add_(1)

tensor([[ 0.2706,  2.4812],
        [ 1.4717,  0.7433]])

In [48]:
print(y)

tensor([[ 0.2706,  2.4812],
        [ 1.4717,  0.7433]])


In [50]:
y.copy_(x)

tensor([[ 0.2706,  2.4812],
        [ 1.4717,  0.7433]])

In [58]:
z = y.clone()

In [59]:
z.add_(1.0)

tensor([[ 2.2706,  4.4812],
        [ 3.4717,  2.7433]])

In [60]:
print(x)

tensor([[ 1.2706,  3.4812],
        [ 2.4717,  1.7433]])


In [61]:
print(y)

tensor([[ 1.2706,  3.4812],
        [ 2.4717,  1.7433]])


In [64]:
y.numpy()

array([[1.2705758, 3.4811933],
       [2.4717336, 1.7432573]], dtype=float32)

In [70]:
yy = y.view(y.size()[0] * y.size()[1])
print(yy)

tensor([ 1.2706,  3.4812,  2.4717,  1.7433])


In [59]:
a = set([3])
print(a)

{3}


In [72]:
print(yy)

tensor([ 2.2706,  4.4812,  3.4717,  2.7433])


In [73]:
print(y)

tensor([[ 2.2706,  4.4812],
        [ 3.4717,  2.7433]])


In [81]:
y = torch.from_numpy( np.ones([3, 3]) )

In [82]:
print(y)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [83]:
torch.cuda.is_available()

False

In [68]:
import math
math.log(2)
math.exp(3)

20.085536923187668

In [66]:
2**2

4

In [7]:
a = [[]]
if a:
    print(1)

1


In [8]:
a = [1, 2, 3]
x = a.pop(0)
print(x)

1


In [33]:
class TreeNode(object):
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

In [45]:
class Codec:
    def serialize(self, root):
        """Encodes atree to a single string.
        
        :type root: TreeNode
        :rtype: str
        """
        #"""  use pre-order serialize. 
        # e.g. 1,2,n,n,3,n,n, and 1,2,n,3,n,n,n, etc.
        data = ''
        if not root:
            return data + ',' + 'n'
        data += ',' + str(root.val)
        data += self.serialize(root.left)
        data += self.serialize(root.right)
        return data
        #"""

    def deserialize(self, data):
        """Decodes your encoded data to tree.
        
        :type data: str
        :rtype: TreeNode
        """
        def deserial_helper(arr): # extract 1 tree and move arr start pointer
            if arr[0] == 'n':
                return None, arr[1:]  # copy, memory inefficient
            p = TreeNode(int(arr[0]))
            p.left, arr = deserial_helper(arr[1:])
            p.right, arr = deserial_helper(arr)    
            return p, arr
        
        arr = data.split(',')[1:]  # remove dummy head
        p, _ = deserial_helper(arr)
        return p

In [53]:
p = TreeNode(1)
p.left = TreeNode(2)
p.left.right = TreeNode(3)

In [54]:
codec = Codec()
data = codec.serialize(p)
print(data)

,1,2,n,3,n,n,n


In [55]:
q = codec.deserialize(data)

In [59]:
q.left.right.val

3

In [3]:
2 ** 2

4

In [10]:
s = 'AA'
rslt = 0
base = 0
for c in s[::-1]:
    x = (26**base)
    y = (ord(c) - ord('A') + 1)
    print(x, y)
    rslt += x * y
    base += 1
print(rslt)

1 1
1 1
2


In [13]:
print(00000000000000000000000000001011)

SyntaxError: invalid token (<ipython-input-13-537a084bf2ff>, line 1)

In [14]:
import math
math.sqrt(15)

3.872983346207417

In [17]:
a = {x:1 for x in range(3)}
a

{0: 1, 1: 1, 2: 1}

In [28]:
from sortedcontainers import SortedList
nums = [1, 2, 3, 1] # [1, 5, 9, 1, 5, 9]
k = 3 #2
t = 0 #3
slist = SortedList()
for i in range(len(nums)):
    if i > k: 
        slist.remove(nums[i-k-1])   
    pos1 = slist.bisect_left(nums[i] - t)
    pos2 = slist.bisect_left(nums[i] + t)

    print(i, pos1, pos2)

    if pos1 != pos2 and pos1 != len(slist): 
        print(True)
        break

    slist.add(nums[i])
print(False)

0 0 0
1 1 1
2 2 2
3 0 0
False


In [81]:
def binsert(arr, v):
    if len(arr) == 0:
        arr.insert(0, v) 
        return 0
    low = 0
    high = len(arr) - 1
    while low <= high:
        mid = low + (high -  low) // 2
        if arr[mid] == v:
            idx = mid
            break
        elif arr[mid] < v:
            low = mid + 1
        else:
            high = mid - 1
            
    if low > high:
        if arr[mid] < v:
            idx = mid + 1
        else: 
            idx = mid 
    arr.insert(idx, v)
    return idx

In [84]:
arr = [5] # [1, 3, 5, 7, 9]
binsert(arr, 6)
print(arr)

[5, 6]


In [58]:
arr = [1, 3, 5, 7, 9]
arr.insert(3, 6)
arr

[1, 3, 5, 6, 7, 9]

In [90]:
nums = [3, 0, 1]
n = len(nums)
nums += [-1]   # nums[n]
cnt = 0
for j in range(n + 1):
    while nums[j] != j and nums[j] != -1:
        #nums[j], nums[nums[j]] = nums[nums[j]], nums[j]
        tmp = nums[j]
        nums[j], nums[tmp] = nums[tmp], nums[j]
        #nums[tmp] = tmp

        cnt += 1
        if cnt < 100:
            print(j, nums)
        else:
            break

0 [-1, 0, 1, 3]
1 [0, -1, 1, 3]
2 [0, 1, -1, 3]
